services:
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ./bethel-social-client/dist:/usr/src/app/public
    build: .
    environment:
      DB_HOST: mysql_server
      DB_PORT: 3306
      SERVER_PORT: 3000
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: socialMedia
    ports:
      - "3000:3000"
    command: sh -c "npm install && node db-init.js && node index.js"
    depends_on:
      mysql_server:
        condition: service_healthy

  mysql_server:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: socialMedia
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD} root password for me is same as user password
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 1s
      timeout: 3s
      retries: 30

  #frontend:
   # build:
    #  context: ./bethel-social-client
     # dockerfile: Dockerfile
    #volumes:
     # - ./bethel-social-client/dist:/usr/src/app/public
    #environment:
     #- NODE_ENV=production
    #command: sh -c "npm install && npm run build"


#exec mysql -uroot -p - to access mysql in the container